BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "joueurs" (
	"id"	INTEGER NOT NULL,
	"joueur_nom"	TEXT NOT NULL,
	"joueur_numero"	INTEGER NOT NULL,
	"joueur_poste"	TEXT NOT NULL,
	"joueur_equipe"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "competitions" (
	"id"	INTEGER NOT NULL UNIQUE,
	"competition_nom"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "equipes" (
	"id"	INTEGER NOT NULL UNIQUE,
	"position_classement"	INTEGER NOT NULL,
	"equipe_nom"	TEXT NOT NULL,
	"competition_nom"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "matchs" (
	"id"	INTEGER NOT NULL UNIQUE,3
	"statut"	TEXT NOT NULL UNIQUE,
	"equipe_domicile_nom"	INTEGER NOT NULL,
	"equipe_exterieure_nom"	INTEGER NOT NULL,
	"score_domicile"	INTEGER NOT NULL,
	"score_exterieure"	INTEGER NOT NULL,
	"competition_nom"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "classements" (
	"id"	INTEGER NOT NULL UNIQUE,
	"competition_nom"	TEXT NOT NULL UNIQUE,
	"equipe_nom"	TEXT NOT NULL UNIQUE,
	"matchs_joues"	INTEGER NOT NULL,
	"nb_points"	INTEGER,
	"nb_victoires" INTEGER,
	"nb_defaites",INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "joueurs" VALUES (1,'Scott Carson',33,'Goalkeeper','Manchester City');
INSERT INTO "joueurs" VALUES (2,'Ederson',31,'Goalkeeper','Manchester City');
INSERT INTO "joueurs" VALUES (3,'Stefan Ortega',18,'Goalkeeper','Manchester City');
INSERT INTO "joueurs" VALUES (4,'Manuel Akanji',25,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (5,'Nathan Aké',6,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (6,'Shea Charles',62,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (7,'Aymeric Laporte',14,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (8,'Rico Lewis',82,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (9,'Benjamin Mendy',22,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (10,'Rúben Dias',3,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (11,'Sergio Gómez',21,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (12,'John Stones',5,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (13,'Kyle Walker',2,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (14,'Bernardo Silva',20,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (15,'Kevin De Bruyne',17,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (16,'Phil Foden',47,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (17,'Jack Grealish',10,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (18,'İlkay Gündoğan',8,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (19,'Nico O''Reilly',75,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (20,'Cole Palmer',80,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (21,'Máximo Perrone',32,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (22,'Kalvin Phillips',4,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (23,'Alex Robertson',93,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (24,'Rodri',16,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (25,'Julián Álvarez',19,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (26,'Erling Haaland',9,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (27,'Ben Knight',96,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (28,'Riyad Mahrez',26,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (29,'Thibaut Courtois',1,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (30,'Diego Piñeiro',38,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (31,'Fran',44,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (32,'Lucas Cañizares',30,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (33,'Luis López',26,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (34,'Andriy Lunin',13,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (35,'Mario de Luis',43,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (36,'David Alaba',4,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (37,'Álvaro Odriozola',16,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (38,'Dani Carvajal',2,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (39,'Eder Militão',3,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (40,'Jesús Vallejo',5,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (41,'Lucas Vázquez',17,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (42,'Marvel',41,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (43,'Ferland Mendy',23,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (44,'Nacho',6,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (45,'Antonio Rüdiger',22,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (46,'Vinícius Tobías',37,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (47,'Arribas',33,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (48,'Eduardo Camavinga',12,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (49,'Dani Ceballos',19,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (50,'Dotor',32,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (51,'Toni Kroos',8,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (52,'Mario Martín',31,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (53,'Luka Modrić',10,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (54,'Nico Paz',40,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (55,'Aurélien Tchouaméni',18,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (56,'Federico Valverde',15,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (57,'Álvaro Rodríguez',39,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (58,'Karim Benzema',9,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (59,'Eden Hazard',7,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (60,'Marco Asensio',11,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (61,'Mariano',24,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (62,'Rodrygo',21,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (63,'Vinícius Júnior',20,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (64,'Gianluigi Donnarumma',99,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (65,'Lucas Lavallée',70,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (66,'Alexandre Letellier',90,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (67,'Sergio Rico',16,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (68,'El Chadaïlle Bitshiabu',31,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (69,'Nehemiah Fernandez',38,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (70,'Achraf Hakimi',2,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (71,'Juan Bernat',14,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (72,'Presnel Kimpembe',3,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (73,'Hugo Lamy',39,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (74,'Marquinhos',5,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (75,'Nordi Mukiele',26,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (76,'Nuno Mendes',25,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (77,'Timothée Pembélé',29,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (78,'Sergio Ramos',4,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (79,'Serif Nhaga',34,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (80,'Carlos Soler',28,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (81,'Danilo',15,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (82,'Fabián Ruiz',8,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (83,'Ismaël Gharbi',35,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (84,'Renato Sanches',18,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (85,'Marco Verratti',6,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (86,'Vitinha',17,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (87,'Warren Zaire-Emery',33,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (88,'Hugo Ekitike',44,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (89,'Ilyes Housni',37,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (90,'Kylian Mbappé',7,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (91,'Lionel Messi',30,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (92,'Neymar',10,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (93,'Gian Marco Crespi',48,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (94,'Giovanni Garofani',41,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (95,'Mattia Perin',36,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (96,'Carlo Pinsoglio',23,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (97,'Simone Scaglia',47,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (98,'Wojciech Szczęsny',1,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (99,'Alex Sandro',12,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (100,'Tommaso Barbieri',42,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (101,'Leonardo Bonucci',19,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (102,'Bremer',3,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (103,'Juan Cuadrado',11,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (104,'Danilo',6,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (105,'Mattia De Sciglio',2,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (106,'Federico Gatti',15,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (107,'Alessandro Riccio',51,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (108,'Daniele Rugani',24,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (109,'Enzo Barrenechea',45,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (110,'Mattia Compagnon',46,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (111,'Nicolò Fagioli',44,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (112,'Mohamed Ihattaren',52,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (113,'Filip Kostić',17,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (114,'Manuel Locatelli',5,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (115,'Fabio Miretti',20,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (116,'Leandro Paredes',32,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (117,'Paul Pogba',10,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (118,'Adrien Rabiot',25,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (119,'Nikola Sekulov',39,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (120,'Alessandro Sersanti',55,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (121,'Federico Chiesa',7,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (122,'Cosimo Da Graca',40,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (123,'Ángel Di María',22,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (124,'Samuel Iling',43,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (125,'Kaio Jorge',21,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (126,'Moise Kean',18,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (127,'Arkadiusz Milik',14,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (128,'Matías Soulé',30,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (129,'Dušan Vlahović',9,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (130,'Ousman Jabang',23,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (131,'James Pantemis',41,'Goalkeeper','Montreal');
INSERT INTO "joueurs" VALUES (132,'Jonathan Sirois',40,'Goalkeeper','Montreal');
INSERT INTO "joueurs" VALUES (133,'Logan Ketterer',1,'Goalkeeper','Montreal');
INSERT INTO "joueurs" VALUES (134,'Joel Waterman',16,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (135,'George Campbell',24,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (136,'Rudy Camacho',4,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (137,'Gabriele Corbo',25,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (138,'Róbert Orri Thorkelsson',26,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (139,'Aarón Herrera',22,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (140,'Zachary Brault-Guillard',15,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (141,'Victor Wanyama',2,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (142,'Samuel Piette',6,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (143,'Ilias Iliadis',5,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (144,'Bryce Duke',10,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (145,'Nathan-Dylan Saliba',19,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (146,'Jojea Kwizera',17,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (147,'Mathieu Choinière',29,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (148,'Ahmed Hamdi',7,'Forward','Montreal');
INSERT INTO "joueurs" VALUES (149,'Sean Rea',27,'Forward','Montreal');
INSERT INTO "joueurs" VALUES (150,'Scott Carson',33,'Goalkeeper','Manchester City');
INSERT INTO "joueurs" VALUES (151,'Ederson',31,'Goalkeeper','Manchester City');
INSERT INTO "joueurs" VALUES (152,'Stefan Ortega',18,'Goalkeeper','Manchester City');
INSERT INTO "joueurs" VALUES (153,'Manuel Akanji',25,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (154,'Nathan Aké',6,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (155,'Shea Charles',62,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (156,'Aymeric Laporte',14,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (157,'Rico Lewis',82,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (158,'Benjamin Mendy',22,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (159,'Rúben Dias',3,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (160,'Sergio Gómez',21,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (161,'John Stones',5,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (162,'Kyle Walker',2,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (163,'Bernardo Silva',20,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (164,'Kevin De Bruyne',17,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (165,'Phil Foden',47,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (166,'Jack Grealish',10,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (167,'İlkay Gündoğan',8,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (168,'Nico O''Reilly',75,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (169,'Cole Palmer',80,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (170,'Máximo Perrone',32,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (171,'Kalvin Phillips',4,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (172,'Alex Robertson',93,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (173,'Rodri',16,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (174,'Julián Álvarez',19,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (175,'Erling Haaland',9,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (176,'Ben Knight',96,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (177,'Riyad Mahrez',26,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (178,'Thibaut Courtois',1,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (179,'Diego Piñeiro',38,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (180,'Fran',44,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (181,'Lucas Cañizares',30,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (182,'Luis López',26,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (183,'Andriy Lunin',13,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (184,'Mario de Luis',43,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (185,'David Alaba',4,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (186,'Álvaro Odriozola',16,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (187,'Dani Carvajal',2,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (188,'Eder Militão',3,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (189,'Jesús Vallejo',5,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (190,'Lucas Vázquez',17,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (191,'Marvel',41,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (192,'Ferland Mendy',23,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (193,'Nacho',6,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (194,'Antonio Rüdiger',22,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (195,'Vinícius Tobías',37,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (196,'Arribas',33,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (197,'Eduardo Camavinga',12,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (198,'Dani Ceballos',19,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (199,'Dotor',32,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (200,'Toni Kroos',8,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (201,'Mario Martín',31,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (202,'Luka Modrić',10,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (203,'Nico Paz',40,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (204,'Aurélien Tchouaméni',18,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (205,'Federico Valverde',15,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (206,'Álvaro Rodríguez',39,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (207,'Karim Benzema',9,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (208,'Eden Hazard',7,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (209,'Marco Asensio',11,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (210,'Mariano',24,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (211,'Rodrygo',21,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (212,'Vinícius Júnior',20,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (213,'Gianluigi Donnarumma',99,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (214,'Lucas Lavallée',70,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (215,'Alexandre Letellier',90,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (216,'Sergio Rico',16,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (217,'El Chadaïlle Bitshiabu',31,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (218,'Nehemiah Fernandez',38,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (219,'Achraf Hakimi',2,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (220,'Juan Bernat',14,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (221,'Presnel Kimpembe',3,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (222,'Hugo Lamy',39,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (223,'Marquinhos',5,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (224,'Nordi Mukiele',26,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (225,'Nuno Mendes',25,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (226,'Timothée Pembélé',29,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (227,'Sergio Ramos',4,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (228,'Serif Nhaga',34,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (229,'Carlos Soler',28,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (230,'Danilo',15,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (231,'Fabián Ruiz',8,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (232,'Ismaël Gharbi',35,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (233,'Renato Sanches',18,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (234,'Marco Verratti',6,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (235,'Vitinha',17,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (236,'Warren Zaire-Emery',33,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (237,'Hugo Ekitike',44,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (238,'Ilyes Housni',37,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (239,'Kylian Mbappé',7,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (240,'Lionel Messi',30,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (241,'Neymar',10,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (242,'Gian Marco Crespi',48,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (243,'Giovanni Garofani',41,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (244,'Mattia Perin',36,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (245,'Carlo Pinsoglio',23,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (246,'Simone Scaglia',47,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (247,'Wojciech Szczęsny',1,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (248,'Alex Sandro',12,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (249,'Tommaso Barbieri',42,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (250,'Leonardo Bonucci',19,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (251,'Bremer',3,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (252,'Juan Cuadrado',11,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (253,'Danilo',6,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (254,'Mattia De Sciglio',2,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (255,'Federico Gatti',15,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (256,'Alessandro Riccio',51,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (257,'Daniele Rugani',24,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (258,'Enzo Barrenechea',45,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (259,'Mattia Compagnon',46,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (260,'Nicolò Fagioli',44,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (261,'Mohamed Ihattaren',52,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (262,'Filip Kostić',17,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (263,'Manuel Locatelli',5,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (264,'Fabio Miretti',20,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (265,'Leandro Paredes',32,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (266,'Paul Pogba',10,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (267,'Adrien Rabiot',25,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (268,'Nikola Sekulov',39,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (269,'Alessandro Sersanti',55,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (270,'Federico Chiesa',7,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (271,'Cosimo Da Graca',40,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (272,'Ángel Di María',22,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (273,'Samuel Iling',43,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (274,'Kaio Jorge',21,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (275,'Moise Kean',18,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (276,'Arkadiusz Milik',14,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (277,'Matías Soulé',30,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (278,'Dušan Vlahović',9,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (279,'Ousman Jabang',23,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (280,'James Pantemis',41,'Goalkeeper','Montreal');
INSERT INTO "joueurs" VALUES (281,'Jonathan Sirois',40,'Goalkeeper','Montreal');
INSERT INTO "joueurs" VALUES (282,'Logan Ketterer',1,'Goalkeeper','Montreal');
INSERT INTO "joueurs" VALUES (283,'Joel Waterman',16,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (284,'George Campbell',24,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (285,'Rudy Camacho',4,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (286,'Gabriele Corbo',25,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (287,'Róbert Orri Thorkelsson',26,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (288,'Aarón Herrera',22,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (289,'Zachary Brault-Guillard',15,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (290,'Victor Wanyama',2,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (291,'Samuel Piette',6,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (292,'Ilias Iliadis',5,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (293,'Bryce Duke',10,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (294,'Nathan-Dylan Saliba',19,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (295,'Jojea Kwizera',17,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (296,'Mathieu Choinière',29,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (297,'Ahmed Hamdi',7,'Forward','Montreal');
INSERT INTO "joueurs" VALUES (298,'Sean Rea',27,'Forward','Montreal');
INSERT INTO "joueurs" VALUES (299,'Scott Carson',33,'Goalkeeper','Manchester City');
INSERT INTO "joueurs" VALUES (300,'Ederson',31,'Goalkeeper','Manchester City');
INSERT INTO "joueurs" VALUES (301,'Stefan Ortega',18,'Goalkeeper','Manchester City');
INSERT INTO "joueurs" VALUES (302,'Manuel Akanji',25,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (303,'Nathan Aké',6,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (304,'Shea Charles',62,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (305,'Aymeric Laporte',14,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (306,'Rico Lewis',82,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (307,'Benjamin Mendy',22,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (308,'Rúben Dias',3,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (309,'Sergio Gómez',21,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (310,'John Stones',5,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (311,'Kyle Walker',2,'Defender','Manchester City');
INSERT INTO "joueurs" VALUES (312,'Bernardo Silva',20,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (313,'Kevin De Bruyne',17,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (314,'Phil Foden',47,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (315,'Jack Grealish',10,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (316,'İlkay Gündoğan',8,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (317,'Nico O''Reilly',75,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (318,'Cole Palmer',80,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (319,'Máximo Perrone',32,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (320,'Kalvin Phillips',4,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (321,'Alex Robertson',93,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (322,'Rodri',16,'Midfielder','Manchester City');
INSERT INTO "joueurs" VALUES (323,'Julián Álvarez',19,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (324,'Erling Haaland',9,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (325,'Ben Knight',96,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (326,'Riyad Mahrez',26,'Forward','Manchester City');
INSERT INTO "joueurs" VALUES (327,'Thibaut Courtois',1,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (328,'Diego Piñeiro',38,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (329,'Fran',44,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (330,'Lucas Cañizares',30,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (331,'Luis López',26,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (332,'Andriy Lunin',13,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (333,'Mario de Luis',43,'Goalkeeper','Real Madrid');
INSERT INTO "joueurs" VALUES (334,'David Alaba',4,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (335,'Álvaro Odriozola',16,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (336,'Dani Carvajal',2,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (337,'Eder Militão',3,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (338,'Jesús Vallejo',5,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (339,'Lucas Vázquez',17,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (340,'Marvel',41,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (341,'Ferland Mendy',23,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (342,'Nacho',6,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (343,'Antonio Rüdiger',22,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (344,'Vinícius Tobías',37,'Defender','Real Madrid');
INSERT INTO "joueurs" VALUES (345,'Arribas',33,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (346,'Eduardo Camavinga',12,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (347,'Dani Ceballos',19,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (348,'Dotor',32,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (349,'Toni Kroos',8,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (350,'Mario Martín',31,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (351,'Luka Modrić',10,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (352,'Nico Paz',40,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (353,'Aurélien Tchouaméni',18,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (354,'Federico Valverde',15,'Midfielder','Real Madrid');
INSERT INTO "joueurs" VALUES (355,'Álvaro Rodríguez',39,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (356,'Karim Benzema',9,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (357,'Eden Hazard',7,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (358,'Marco Asensio',11,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (359,'Mariano',24,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (360,'Rodrygo',21,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (361,'Vinícius Júnior',20,'Forward','Real Madrid');
INSERT INTO "joueurs" VALUES (362,'Gianluigi Donnarumma',99,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (363,'Lucas Lavallée',70,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (364,'Alexandre Letellier',90,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (365,'Sergio Rico',16,'Goalkeeper','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (366,'El Chadaïlle Bitshiabu',31,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (367,'Nehemiah Fernandez',38,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (368,'Achraf Hakimi',2,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (369,'Juan Bernat',14,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (370,'Presnel Kimpembe',3,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (371,'Hugo Lamy',39,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (372,'Marquinhos',5,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (373,'Nordi Mukiele',26,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (374,'Nuno Mendes',25,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (375,'Timothée Pembélé',29,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (376,'Sergio Ramos',4,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (377,'Serif Nhaga',34,'Defender','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (378,'Carlos Soler',28,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (379,'Danilo',15,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (380,'Fabián Ruiz',8,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (381,'Ismaël Gharbi',35,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (382,'Renato Sanches',18,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (383,'Marco Verratti',6,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (384,'Vitinha',17,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (385,'Warren Zaire-Emery',33,'Midfielder','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (386,'Hugo Ekitike',44,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (387,'Ilyes Housni',37,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (388,'Kylian Mbappé',7,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (389,'Lionel Messi',30,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (390,'Neymar',10,'Forward','Paris Saint-Germain');
INSERT INTO "joueurs" VALUES (391,'Gian Marco Crespi',48,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (392,'Giovanni Garofani',41,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (393,'Mattia Perin',36,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (394,'Carlo Pinsoglio',23,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (395,'Simone Scaglia',47,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (396,'Wojciech Szczęsny',1,'Goalkeeper','Juventus');
INSERT INTO "joueurs" VALUES (397,'Alex Sandro',12,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (398,'Tommaso Barbieri',42,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (399,'Leonardo Bonucci',19,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (400,'Bremer',3,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (401,'Juan Cuadrado',11,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (402,'Danilo',6,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (403,'Mattia De Sciglio',2,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (404,'Federico Gatti',15,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (405,'Alessandro Riccio',51,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (406,'Daniele Rugani',24,'Defender','Juventus');
INSERT INTO "joueurs" VALUES (407,'Enzo Barrenechea',45,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (408,'Mattia Compagnon',46,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (409,'Nicolò Fagioli',44,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (410,'Mohamed Ihattaren',52,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (411,'Filip Kostić',17,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (412,'Manuel Locatelli',5,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (413,'Fabio Miretti',20,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (414,'Leandro Paredes',32,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (415,'Paul Pogba',10,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (416,'Adrien Rabiot',25,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (417,'Nikola Sekulov',39,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (418,'Alessandro Sersanti',55,'Midfielder','Juventus');
INSERT INTO "joueurs" VALUES (419,'Federico Chiesa',7,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (420,'Cosimo Da Graca',40,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (421,'Ángel Di María',22,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (422,'Samuel Iling',43,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (423,'Kaio Jorge',21,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (424,'Moise Kean',18,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (425,'Arkadiusz Milik',14,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (426,'Matías Soulé',30,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (427,'Dušan Vlahović',9,'Forward','Juventus');
INSERT INTO "joueurs" VALUES (428,'Ousman Jabang',23,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (429,'James Pantemis',41,'Goalkeeper','Montreal');
INSERT INTO "joueurs" VALUES (430,'Jonathan Sirois',40,'Goalkeeper','Montreal');
INSERT INTO "joueurs" VALUES (431,'Logan Ketterer',1,'Goalkeeper','Montreal');
INSERT INTO "joueurs" VALUES (432,'Joel Waterman',16,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (433,'George Campbell',24,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (434,'Rudy Camacho',4,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (435,'Gabriele Corbo',25,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (436,'Róbert Orri Thorkelsson',26,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (437,'Aarón Herrera',22,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (438,'Zachary Brault-Guillard',15,'Defender','Montreal');
INSERT INTO "joueurs" VALUES (439,'Victor Wanyama',2,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (440,'Samuel Piette',6,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (441,'Ilias Iliadis',5,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (442,'Bryce Duke',10,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (443,'Nathan-Dylan Saliba',19,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (444,'Jojea Kwizera',17,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (445,'Mathieu Choinière',29,'Midfielder','Montreal');
INSERT INTO "joueurs" VALUES (446,'Ahmed Hamdi',7,'Forward','Montreal');
INSERT INTO "joueurs" VALUES (447,'Sean Rea',27,'Forward','Montreal');
INSERT INTO "competitions" VALUES (1,'Premier League');
INSERT INTO "competitions" VALUES (2,'Liga');
INSERT INTO "competitions" VALUES (3,'Ligue 1');
INSERT INTO "competitions" VALUES (4,'Serie A');
INSERT INTO "competitions" VALUES (5,'MLS');
INSERT INTO "competitions" VALUES (6,'Premier League');
INSERT INTO "competitions" VALUES (7,'Liga');
INSERT INTO "competitions" VALUES (8,'Ligue 1');
INSERT INTO "competitions" VALUES (9,'Serie A');
INSERT INTO "competitions" VALUES (10,'MLS');
INSERT INTO "competitions" VALUES (11,'Premier League');
INSERT INTO "competitions" VALUES (12,'Liga');
INSERT INTO "competitions" VALUES (13,'Ligue 1');
INSERT INTO "competitions" VALUES (14,'Serie A');
INSERT INTO "competitions" VALUES (15,'MLS');
INSERT INTO "equipes" VALUES (1,1,'Manchester City','Premier League');
INSERT INTO "equipes" VALUES (2,2,'Arsenal','Premier League');
INSERT INTO "equipes" VALUES (3,3,'Manchester United','Premier League');
INSERT INTO "equipes" VALUES (4,4,'Newcastle','Premier League');
INSERT INTO "equipes" VALUES (5,5,'Liverpool','Premier League');
INSERT INTO "equipes" VALUES (6,6,'Brighton','Premier League');
INSERT INTO "equipes" VALUES (7,7,'Aston Villa','Premier League');
INSERT INTO "equipes" VALUES (8,8,'Tottenham','Premier League');
INSERT INTO "equipes" VALUES (9,9,'Brentford','Premier League');
INSERT INTO "equipes" VALUES (10,10,'Fulham','Premier League');
INSERT INTO "equipes" VALUES (11,11,'Crystal Palace','Premier League');
INSERT INTO "equipes" VALUES (12,12,'Chelsea','Premier League');
INSERT INTO "equipes" VALUES (13,13,'Wolverhampton','Premier League');
INSERT INTO "equipes" VALUES (14,14,'West Ham','Premier League');
INSERT INTO "equipes" VALUES (15,15,'Bournemouth','Premier League');
INSERT INTO "equipes" VALUES (16,16,'Nottingham Forest','Premier League');
INSERT INTO "equipes" VALUES (17,17,'Everton','Premier League');
INSERT INTO "equipes" VALUES (18,18,'Leicester','Premier League');
INSERT INTO "equipes" VALUES (19,19,'Leeds','Premier League');
INSERT INTO "equipes" VALUES (20,20,'Southampton','Premier League');
INSERT INTO "equipes" VALUES (21,1,'FC Barcelone','Liga');
INSERT INTO "equipes" VALUES (22,2,'Real Madrid','Liga');
INSERT INTO "equipes" VALUES (23,3,'Atlético de Madrid','Liga');
INSERT INTO "equipes" VALUES (24,4,'Real Sociedad','Liga');
INSERT INTO "equipes" VALUES (25,5,'Villarreal','Liga');
INSERT INTO "equipes" VALUES (26,6,'Betis Séville','Liga');
INSERT INTO "equipes" VALUES (27,7,'Osasuna','Liga');
INSERT INTO "equipes" VALUES (28,8,'Athletic Bilbao','Liga');
INSERT INTO "equipes" VALUES (29,9,'Majorque','Liga');
INSERT INTO "equipes" VALUES (30,10,'Gérone','Liga');
INSERT INTO "equipes" VALUES (31,11,'Rayo Vallecano','Liga');
INSERT INTO "equipes" VALUES (32,12,'Séville FC','Liga');
INSERT INTO "equipes" VALUES (33,13,'Celta Vigo','Liga');
INSERT INTO "equipes" VALUES (34,14,'Cadix','Liga');
INSERT INTO "equipes" VALUES (35,15,'Getafe','Liga');
INSERT INTO "equipes" VALUES (36,16,'Valence CF','Liga');
INSERT INTO "equipes" VALUES (37,17,'Almeria','Liga');
INSERT INTO "equipes" VALUES (38,18,'Valladolid','Liga');
INSERT INTO "equipes" VALUES (39,19,'Espanyol Barcelone','Liga');
INSERT INTO "equipes" VALUES (40,20,'Elche','Liga');
INSERT INTO "equipes" VALUES (41,1,'Paris-SG','Ligue 1');
INSERT INTO "equipes" VALUES (42,2,'Lens','Ligue 1');
INSERT INTO "equipes" VALUES (43,3,'Marseille','Ligue 1');
INSERT INTO "equipes" VALUES (44,4,'Rennes','Ligue 1');
INSERT INTO "equipes" VALUES (45,5,'Lille','Ligue 1');
INSERT INTO "equipes" VALUES (46,6,'Monaco','Ligue 1');
INSERT INTO "equipes" VALUES (47,7,'Lyon','Ligue 1');
INSERT INTO "equipes" VALUES (48,8,'Clermont','Ligue 1');
INSERT INTO "equipes" VALUES (49,9,'Nice','Ligue 1');
INSERT INTO "equipes" VALUES (50,10,'Lorient','Ligue 1');
INSERT INTO "equipes" VALUES (51,11,'Reims','Ligue 1');
INSERT INTO "equipes" VALUES (52,12,'Montpellier','Ligue 1');
INSERT INTO "equipes" VALUES (53,13,'Toulouse','Ligue 1');
INSERT INTO "equipes" VALUES (54,14,'Brest','Ligue 1');
INSERT INTO "equipes" VALUES (55,15,'Strasbourg','Ligue 1');
INSERT INTO "equipes" VALUES (56,16,'Nantes','Ligue 1');
INSERT INTO "equipes" VALUES (57,17,'Auxerre','Ligue 1');
INSERT INTO "equipes" VALUES (58,18,'AC Ajaccio','Ligue 1');
INSERT INTO "equipes" VALUES (59,19,'Troyes','Ligue 1');
INSERT INTO "equipes" VALUES (60,20,'Angers','Ligue 1');
INSERT INTO "equipes" VALUES (61,1,'Naples','Serie A');
INSERT INTO "equipes" VALUES (62,2,'Lazio Rome','Serie A');
INSERT INTO "equipes" VALUES (63,3,'Inter Milan','Serie A');
INSERT INTO "equipes" VALUES (64,4,'AC Milan','Serie A');
INSERT INTO "equipes" VALUES (65,5,'Atalanta Bergame','Serie A');
INSERT INTO "equipes" VALUES (66,6,'AS Rome','Serie A');
INSERT INTO "equipes" VALUES (67,7,'Juventus Turin','Serie A');
INSERT INTO "equipes" VALUES (68,8,'Fiorentina','Serie A');
INSERT INTO "equipes" VALUES (69,9,'Bologne','Serie A');
INSERT INTO "equipes" VALUES (70,10,'Torino','Serie A');
INSERT INTO "equipes" VALUES (71,11,'Monza','Serie A');
INSERT INTO "equipes" VALUES (72,12,'Udinese','Serie A');
INSERT INTO "equipes" VALUES (73,13,'Sassuolo','Serie A');
INSERT INTO "equipes" VALUES (74,14,'Empoli','Serie A');
INSERT INTO "equipes" VALUES (75,15,'Salernitana','Serie A');
INSERT INTO "equipes" VALUES (76,16,'Lecce','Serie A');
INSERT INTO "equipes" VALUES (77,17,'La Spezia','Serie A');
INSERT INTO "equipes" VALUES (78,18,'Hellas Vérone','Serie A');
INSERT INTO "equipes" VALUES (79,19,'Cremonese','Serie A');
INSERT INTO "equipes" VALUES (80,20,'Sampdoria','Serie A');
INSERT INTO "equipes" VALUES (81,1,'Cincinnati','MLS');
INSERT INTO "equipes" VALUES (82,2,'Nashville','MLS');
INSERT INTO "equipes" VALUES (83,3,'Philadelphie','MLS');
INSERT INTO "equipes" VALUES (84,4,'New England','MLS');
INSERT INTO "equipes" VALUES (85,5,'Atlanta United','MLS');
INSERT INTO "equipes" VALUES (86,6,'Columbus','MLS');
INSERT INTO "equipes" VALUES (87,7,'Orlando','MLS');
INSERT INTO "equipes" VALUES (88,8,'DC United','MLS');
INSERT INTO "equipes" VALUES (89,9,'Montréal','MLS');
INSERT INTO "equipes" VALUES (90,10,'Charlotte','MLS');
INSERT INTO "equipes" VALUES (91,11,'New York','MLS');
INSERT INTO "equipes" VALUES (92,12,'Toronto','MLS');
INSERT INTO "equipes" VALUES (93,13,'NYCFC','MLS');
INSERT INTO "equipes" VALUES (94,14,'Chicago','MLS');
INSERT INTO "equipes" VALUES (95,15,'Inter Miami','MLS');
INSERT INTO "equipes" VALUES (96,1,'Manchester City','Premier League');
INSERT INTO "equipes" VALUES (97,2,'Arsenal','Premier League');
INSERT INTO "equipes" VALUES (98,3,'Manchester United','Premier League');
INSERT INTO "equipes" VALUES (99,4,'Newcastle','Premier League');
INSERT INTO "equipes" VALUES (100,5,'Liverpool','Premier League');
INSERT INTO "equipes" VALUES (101,6,'Brighton','Premier League');
INSERT INTO "equipes" VALUES (102,7,'Aston Villa','Premier League');
INSERT INTO "equipes" VALUES (103,8,'Tottenham','Premier League');
INSERT INTO "equipes" VALUES (104,9,'Brentford','Premier League');
INSERT INTO "equipes" VALUES (105,10,'Fulham','Premier League');
INSERT INTO "equipes" VALUES (106,11,'Crystal Palace','Premier League');
INSERT INTO "equipes" VALUES (107,12,'Chelsea','Premier League');
INSERT INTO "equipes" VALUES (108,13,'Wolverhampton','Premier League');
INSERT INTO "equipes" VALUES (109,14,'West Ham','Premier League');
INSERT INTO "equipes" VALUES (110,15,'Bournemouth','Premier League');
INSERT INTO "equipes" VALUES (111,16,'Nottingham Forest','Premier League');
INSERT INTO "equipes" VALUES (112,17,'Everton','Premier League');
INSERT INTO "equipes" VALUES (113,18,'Leicester','Premier League');
INSERT INTO "equipes" VALUES (114,19,'Leeds','Premier League');
INSERT INTO "equipes" VALUES (115,20,'Southampton','Premier League');
INSERT INTO "equipes" VALUES (116,1,'FC Barcelone','Liga');
INSERT INTO "equipes" VALUES (117,2,'Real Madrid','Liga');
INSERT INTO "equipes" VALUES (118,3,'Atlético de Madrid','Liga');
INSERT INTO "equipes" VALUES (119,4,'Real Sociedad','Liga');
INSERT INTO "equipes" VALUES (120,5,'Villarreal','Liga');
INSERT INTO "equipes" VALUES (121,6,'Betis Séville','Liga');
INSERT INTO "equipes" VALUES (122,7,'Osasuna','Liga');
INSERT INTO "equipes" VALUES (123,8,'Athletic Bilbao','Liga');
INSERT INTO "equipes" VALUES (124,9,'Majorque','Liga');
INSERT INTO "equipes" VALUES (125,10,'Gérone','Liga');
INSERT INTO "equipes" VALUES (126,11,'Rayo Vallecano','Liga');
INSERT INTO "equipes" VALUES (127,12,'Séville FC','Liga');
INSERT INTO "equipes" VALUES (128,13,'Celta Vigo','Liga');
INSERT INTO "equipes" VALUES (129,14,'Cadix','Liga');
INSERT INTO "equipes" VALUES (130,15,'Getafe','Liga');
INSERT INTO "equipes" VALUES (131,16,'Valence CF','Liga');
INSERT INTO "equipes" VALUES (132,17,'Almeria','Liga');
INSERT INTO "equipes" VALUES (133,18,'Valladolid','Liga');
INSERT INTO "equipes" VALUES (134,19,'Espanyol Barcelone','Liga');
INSERT INTO "equipes" VALUES (135,20,'Elche','Liga');
INSERT INTO "equipes" VALUES (136,1,'Paris-SG','Ligue 1');
INSERT INTO "equipes" VALUES (137,2,'Lens','Ligue 1');
INSERT INTO "equipes" VALUES (138,3,'Marseille','Ligue 1');
INSERT INTO "equipes" VALUES (139,4,'Rennes','Ligue 1');
INSERT INTO "equipes" VALUES (140,5,'Lille','Ligue 1');
INSERT INTO "equipes" VALUES (141,6,'Monaco','Ligue 1');
INSERT INTO "equipes" VALUES (142,7,'Lyon','Ligue 1');
INSERT INTO "equipes" VALUES (143,8,'Clermont','Ligue 1');
INSERT INTO "equipes" VALUES (144,9,'Nice','Ligue 1');
INSERT INTO "equipes" VALUES (145,10,'Lorient','Ligue 1');
INSERT INTO "equipes" VALUES (146,11,'Reims','Ligue 1');
INSERT INTO "equipes" VALUES (147,12,'Montpellier','Ligue 1');
INSERT INTO "equipes" VALUES (148,13,'Toulouse','Ligue 1');
INSERT INTO "equipes" VALUES (149,14,'Brest','Ligue 1');
INSERT INTO "equipes" VALUES (150,15,'Strasbourg','Ligue 1');
INSERT INTO "equipes" VALUES (151,16,'Nantes','Ligue 1');
INSERT INTO "equipes" VALUES (152,17,'Auxerre','Ligue 1');
INSERT INTO "equipes" VALUES (153,18,'AC Ajaccio','Ligue 1');
INSERT INTO "equipes" VALUES (154,19,'Troyes','Ligue 1');
INSERT INTO "equipes" VALUES (155,20,'Angers','Ligue 1');
INSERT INTO "equipes" VALUES (156,1,'Naples','Serie A');
INSERT INTO "equipes" VALUES (157,2,'Lazio Rome','Serie A');
INSERT INTO "equipes" VALUES (158,3,'Inter Milan','Serie A');
INSERT INTO "equipes" VALUES (159,4,'AC Milan','Serie A');
INSERT INTO "equipes" VALUES (160,5,'Atalanta Bergame','Serie A');
INSERT INTO "equipes" VALUES (161,6,'AS Rome','Serie A');
INSERT INTO "equipes" VALUES (162,7,'Juventus Turin','Serie A');
INSERT INTO "equipes" VALUES (163,8,'Fiorentina','Serie A');
INSERT INTO "equipes" VALUES (164,9,'Bologne','Serie A');
INSERT INTO "equipes" VALUES (165,10,'Torino','Serie A');
INSERT INTO "equipes" VALUES (166,11,'Monza','Serie A');
INSERT INTO "equipes" VALUES (167,12,'Udinese','Serie A');
INSERT INTO "equipes" VALUES (168,13,'Sassuolo','Serie A');
INSERT INTO "equipes" VALUES (169,14,'Empoli','Serie A');
INSERT INTO "equipes" VALUES (170,15,'Salernitana','Serie A');
INSERT INTO "equipes" VALUES (171,16,'Lecce','Serie A');
INSERT INTO "equipes" VALUES (172,17,'La Spezia','Serie A');
INSERT INTO "equipes" VALUES (173,18,'Hellas Vérone','Serie A');
INSERT INTO "equipes" VALUES (174,19,'Cremonese','Serie A');
INSERT INTO "equipes" VALUES (175,20,'Sampdoria','Serie A');
INSERT INTO "equipes" VALUES (176,1,'Cincinnati','MLS');
INSERT INTO "equipes" VALUES (177,2,'Nashville','MLS');
INSERT INTO "equipes" VALUES (178,3,'Philadelphie','MLS');
INSERT INTO "equipes" VALUES (179,4,'New England','MLS');
INSERT INTO "equipes" VALUES (180,5,'Atlanta United','MLS');
INSERT INTO "equipes" VALUES (181,6,'Columbus','MLS');
INSERT INTO "equipes" VALUES (182,7,'Orlando','MLS');
INSERT INTO "equipes" VALUES (183,8,'DC United','MLS');
INSERT INTO "equipes" VALUES (184,9,'Montréal','MLS');
INSERT INTO "equipes" VALUES (185,10,'Charlotte','MLS');
INSERT INTO "equipes" VALUES (186,11,'New York','MLS');
INSERT INTO "equipes" VALUES (187,12,'Toronto','MLS');
INSERT INTO "equipes" VALUES (188,13,'NYCFC','MLS');
INSERT INTO "equipes" VALUES (189,14,'Chicago','MLS');
INSERT INTO "equipes" VALUES (190,15,'Inter Miami','MLS');
INSERT INTO "equipes" VALUES (191,1,'Manchester City','Premier League');
INSERT INTO "equipes" VALUES (192,2,'Arsenal','Premier League');
INSERT INTO "equipes" VALUES (193,3,'Manchester United','Premier League');
INSERT INTO "equipes" VALUES (194,4,'Newcastle','Premier League');
INSERT INTO "equipes" VALUES (195,5,'Liverpool','Premier League');
INSERT INTO "equipes" VALUES (196,6,'Brighton','Premier League');
INSERT INTO "equipes" VALUES (197,7,'Aston Villa','Premier League');
INSERT INTO "equipes" VALUES (198,8,'Tottenham','Premier League');
INSERT INTO "equipes" VALUES (199,9,'Brentford','Premier League');
INSERT INTO "equipes" VALUES (200,10,'Fulham','Premier League');
INSERT INTO "equipes" VALUES (201,11,'Crystal Palace','Premier League');
INSERT INTO "equipes" VALUES (202,12,'Chelsea','Premier League');
INSERT INTO "equipes" VALUES (203,13,'Wolverhampton','Premier League');
INSERT INTO "equipes" VALUES (204,14,'West Ham','Premier League');
INSERT INTO "equipes" VALUES (205,15,'Bournemouth','Premier League');
INSERT INTO "equipes" VALUES (206,16,'Nottingham Forest','Premier League');
INSERT INTO "equipes" VALUES (207,17,'Everton','Premier League');
INSERT INTO "equipes" VALUES (208,18,'Leicester','Premier League');
INSERT INTO "equipes" VALUES (209,19,'Leeds','Premier League');
INSERT INTO "equipes" VALUES (210,20,'Southampton','Premier League');
INSERT INTO "equipes" VALUES (211,1,'FC Barcelone','Liga');
INSERT INTO "equipes" VALUES (212,2,'Real Madrid','Liga');
INSERT INTO "equipes" VALUES (213,3,'Atlético de Madrid','Liga');
INSERT INTO "equipes" VALUES (214,4,'Real Sociedad','Liga');
INSERT INTO "equipes" VALUES (215,5,'Villarreal','Liga');
INSERT INTO "equipes" VALUES (216,6,'Betis Séville','Liga');
INSERT INTO "equipes" VALUES (217,7,'Osasuna','Liga');
INSERT INTO "equipes" VALUES (218,8,'Athletic Bilbao','Liga');
INSERT INTO "equipes" VALUES (219,9,'Majorque','Liga');
INSERT INTO "equipes" VALUES (220,10,'Gérone','Liga');
INSERT INTO "equipes" VALUES (221,11,'Rayo Vallecano','Liga');
INSERT INTO "equipes" VALUES (222,12,'Séville FC','Liga');
INSERT INTO "equipes" VALUES (223,13,'Celta Vigo','Liga');
INSERT INTO "equipes" VALUES (224,14,'Cadix','Liga');
INSERT INTO "equipes" VALUES (225,15,'Getafe','Liga');
INSERT INTO "equipes" VALUES (226,16,'Valence CF','Liga');
INSERT INTO "equipes" VALUES (227,17,'Almeria','Liga');
INSERT INTO "equipes" VALUES (228,18,'Valladolid','Liga');
INSERT INTO "equipes" VALUES (229,19,'Espanyol Barcelone','Liga');
INSERT INTO "equipes" VALUES (230,20,'Elche','Liga');
INSERT INTO "equipes" VALUES (231,1,'Paris-SG','Ligue 1');
INSERT INTO "equipes" VALUES (232,2,'Lens','Ligue 1');
INSERT INTO "equipes" VALUES (233,3,'Marseille','Ligue 1');
INSERT INTO "equipes" VALUES (234,4,'Rennes','Ligue 1');
INSERT INTO "equipes" VALUES (235,5,'Lille','Ligue 1');
INSERT INTO "equipes" VALUES (236,6,'Monaco','Ligue 1');
INSERT INTO "equipes" VALUES (237,7,'Lyon','Ligue 1');
INSERT INTO "equipes" VALUES (238,8,'Clermont','Ligue 1');
INSERT INTO "equipes" VALUES (239,9,'Nice','Ligue 1');
INSERT INTO "equipes" VALUES (240,10,'Lorient','Ligue 1');
INSERT INTO "equipes" VALUES (241,11,'Reims','Ligue 1');
INSERT INTO "equipes" VALUES (242,12,'Montpellier','Ligue 1');
INSERT INTO "equipes" VALUES (243,13,'Toulouse','Ligue 1');
INSERT INTO "equipes" VALUES (244,14,'Brest','Ligue 1');
INSERT INTO "equipes" VALUES (245,15,'Strasbourg','Ligue 1');
INSERT INTO "equipes" VALUES (246,16,'Nantes','Ligue 1');
INSERT INTO "equipes" VALUES (247,17,'Auxerre','Ligue 1');
INSERT INTO "equipes" VALUES (248,18,'AC Ajaccio','Ligue 1');
INSERT INTO "equipes" VALUES (249,19,'Troyes','Ligue 1');
INSERT INTO "equipes" VALUES (250,20,'Angers','Ligue 1');
INSERT INTO "equipes" VALUES (251,1,'Naples','Serie A');
INSERT INTO "equipes" VALUES (252,2,'Lazio Rome','Serie A');
INSERT INTO "equipes" VALUES (253,3,'Inter Milan','Serie A');
INSERT INTO "equipes" VALUES (254,4,'AC Milan','Serie A');
INSERT INTO "equipes" VALUES (255,5,'Atalanta Bergame','Serie A');
INSERT INTO "equipes" VALUES (256,6,'AS Rome','Serie A');
INSERT INTO "equipes" VALUES (257,7,'Juventus Turin','Serie A');
INSERT INTO "equipes" VALUES (258,8,'Fiorentina','Serie A');
INSERT INTO "equipes" VALUES (259,9,'Bologne','Serie A');
INSERT INTO "equipes" VALUES (260,10,'Torino','Serie A');
INSERT INTO "equipes" VALUES (261,11,'Monza','Serie A');
INSERT INTO "equipes" VALUES (262,12,'Udinese','Serie A');
INSERT INTO "equipes" VALUES (263,13,'Sassuolo','Serie A');
INSERT INTO "equipes" VALUES (264,14,'Empoli','Serie A');
INSERT INTO "equipes" VALUES (265,15,'Salernitana','Serie A');
INSERT INTO "equipes" VALUES (266,16,'Lecce','Serie A');
INSERT INTO "equipes" VALUES (267,17,'La Spezia','Serie A');
INSERT INTO "equipes" VALUES (268,18,'Hellas Vérone','Serie A');
INSERT INTO "equipes" VALUES (269,19,'Cremonese','Serie A');
INSERT INTO "equipes" VALUES (270,20,'Sampdoria','Serie A');
INSERT INTO "equipes" VALUES (271,1,'Cincinnati','MLS');
INSERT INTO "equipes" VALUES (272,2,'Nashville','MLS');
INSERT INTO "equipes" VALUES (273,3,'Philadelphie','MLS');
INSERT INTO "equipes" VALUES (274,4,'New England','MLS');
INSERT INTO "equipes" VALUES (275,5,'Atlanta United','MLS');
INSERT INTO "equipes" VALUES (276,6,'Columbus','MLS');
INSERT INTO "equipes" VALUES (277,7,'Orlando','MLS');
INSERT INTO "equipes" VALUES (278,8,'DC United','MLS');
INSERT INTO "equipes" VALUES (279,9,'Montréal','MLS');
INSERT INTO "equipes" VALUES (280,10,'Charlotte','MLS');
INSERT INTO "equipes" VALUES (281,11,'New York','MLS');
INSERT INTO "equipes" VALUES (282,12,'Toronto','MLS');
INSERT INTO "equipes" VALUES (283,13,'NYCFC','MLS');
INSERT INTO "equipes" VALUES (284,14,'Chicago','MLS');
INSERT INTO "equipes" VALUES (285,15,'Inter Miami','MLS');
INSERT INTO "matchs"  VALUES (286,'Terminé', 'Manchester United', 'Manchester City', 2, 0, 'Premier League');
INSERT INTO "matchs"  VALUES (287,'En cours', 'Chelsea', 'Liverpool', 1, 1, 'Premier League');
INSERT INTO "matchs"  VALUES (288,'À venir', 'Arsenal', 'Tottenham Hotspur', 0, 0, 'Premier League');
INSERT INTO "matchs"  VALUES (289,'Terminé', 'Brighton', 'Brentford', 3, 1, 'Premier League');
INSERT INTO "matchs"  VALUES (290,'En cours', 'Everton', 'Newcastle', 2, 2, 'Premier League');
INSERT INTO "matchs"  VALUES (291,'À venir', 'Fulham', 'Leeds', 0, 0, 'Premier League');
INSERT INTO "matchs"  VALUES (292,'Terminé', 'Real Madrid', 'Barcelona', 2, 1, 'Liga');
INSERT INTO "matchs"  VALUES (293,'En cours', 'Atletico Madrid', 'Sevilla', 0, 0, 'Liga');
INSERT INTO "matchs"  VALUES (294,'À venir', 'Valencia', 'Villarreal', 0, 0, 'Liga');
INSERT INTO "matchs"  VALUES (295,'Terminé', 'Levante', 'Osasuna', 2, 1, 'Liga');
INSERT INTO "matchs"  VALUES (296,'En cours', 'Gérone', 'Cadiz', 0, 0, 'Liga');
INSERT INTO "matchs"  VALUES (297,'À venir', 'Almeria', 'Getafe', 0, 0, 'Liga');
INSERT INTO "matchs"  VALUES (298,'Terminé', 'Paris Saint-Germain', 'Olympique de Marseille', 3, 0, 'Ligue 1');
INSERT INTO "matchs"  VALUES (299,'En cours', 'Lille', 'Lyon', 1, 1, 'Ligue 1');
INSERT INTO "matchs"  VALUES (300,'À venir', 'Monaco', 'Nice', 0, 0, 'Ligue 1');
INSERT INTO "matchs"  VALUES (301,'Terminé', 'Strasbourg', 'Clermont', 3, 0, 'Ligue 1');
INSERT INTO "matchs"  VALUES (302,'En cours', 'Lens', 'Lorient', 1, 0, 'Ligue 1');
INSERT INTO "matchs"  VALUES (303,'À venir', 'Rennes', 'Brest', 0, 0, 'Ligue 1');
INSERT INTO "matchs"  VALUES (304,'Terminé', 'Juventus', 'AC Milan', 2, 1, 'Serie A');
INSERT INTO "matchs"  VALUES (305,'En cours', 'Inter Milan', 'AS Roma', 0, 0, 'Serie A');
INSERT INTO "matchs"  VALUES (306,'À venir', 'Napoli', 'Lazio', 0, 0, 'Serie A');
INSERT INTO "matchs"  VALUES (307,'Terminé', 'Lecce', 'Empoli', 2, 1, 'Serie A');
INSERT INTO "matchs"  VALUES (308,'En cours', 'Udinese', 'Torino', 0, 2, 'Serie A');
INSERT INTO "matchs"  VALUES (309,'À venir', 'Cremonese', 'Sampdoria', 0, 0, 'Serie A');
INSERT INTO "matchs"  VALUES (310,'Terminé', 'Los Angeles FC', 'Seattle Sounders', 1, 0, 'MLS');
INSERT INTO "matchs"  VALUES (311,'En cours', 'Atlanta United', 'New York City FC', 0, 0, 'MLS');
INSERT INTO "matchs"  VALUES (312,'À venir', 'Toronto FC', 'Chicago Fire', 0, 0, 'MLS');
INSERT INTO "matchs"  VALUES (313,'Terminé', 'Nashville', 'Columbus', 1, 0, 'MLS');
INSERT INTO "matchs"  VALUES (314,'En cours', 'Philadelphie', 'Orlando', 0, 0, 'MLS');
INSERT INTO "matchs"  VALUES (315,'À venir', 'Montréal', 'Charlotte', 0, 0, 'MLS');

INSERT INTO "classements" VALUES(316,'premier league','Manchester City',38,111,37,1);
INSERT INTO "classements" VALUES(317,'premier league','Arsenal',38,108,36,2);
INSERT INTO "classements" VALUES(318,'premier league','Manchester United',38,105,35,3);
INSERT INTO "classements" VALUES(319,'premier league','Tottenham',38,102,34,4);
INSERT INTO "classements" VALUES(320,'premier league','Chelsea',38,99,33,5);
INSERT INTO "classements" VALUES(321,'premier league','NewCastle',38,96,32,6);
INSERT INTO "classements" VALUES(322,'premier league','Sheffield',38,93,31,7);
INSERT INTO "classements" VALUES(323,'premier league','Wolverhampton',38,90,30,8);
INSERT INTO "classements" VALUES(324,'premier league','Liverpool',38,90,30,8);
INSERT INTO "classements" VALUES(325,'premier league','Everton',38,84,28,10);


INSERT INTO "classements" VALUES(326,'Liga Santader','Real Madrid',38,110,33,1);
INSERT INTO "classements" VALUES(327,'Liga Santader','Barcelone',38,107,36,2);
INSERT INTO "classements" VALUES(328,'Liga Santader','Atletico',38,106,35,3);
INSERT INTO "classements" VALUES(329,'Liga Santader','Valence',38,105,34,4);
INSERT INTO "classements" VALUES(330,'Liga Santader','Seville',38,100,33,5);
INSERT INTO "classements" VALUES(331,'Liga Santader','Rayo',38,99,32,6);
INSERT INTO "classements" VALUES(332,'Liga Santader','Getafe',38,97,31,7);
INSERT INTO "classements" VALUES(333,'Liga Santader','Levante',38,96,30,8);
INSERT INTO "classements" VALUES(334,'Liga Santader','Villareal',38,95,30,8);
INSERT INTO "classements" VALUES(335,'Liga Santader','Bilbao',38,94,28,10);


INSERT INTO "classements" VALUES(336,'Serie A','Juventus',38,109,34,1);
INSERT INTO "classements" VALUES(337,'Serie A','Ac Milan',38,100,36,2);
INSERT INTO "classements" VALUES(338,'Serie A','Inter Milan',38,105,35,3);
INSERT INTO "classements" VALUES(339,'Serie A','Fiorentina',38,102,34,4);
INSERT INTO "classements" VALUES(340,'Serie A','Calgary',38,99,33,5);
INSERT INTO "classements" VALUES(341,'Serie A','Naples',38,95,32,6);
INSERT INTO "classements" VALUES(342,'Serie A','Sassuolo',38,94,31,7);
INSERT INTO "classements" VALUES(343,'Serie A','Parmes',38,92,30,8);
INSERT INTO "classements" VALUES(344,'Serie A','Torino',38,90,30,8);
INSERT INTO "classements" VALUES(345,'Serie A','Hellas verone',38,84,28,10);

INSERT INTO "classements" VALUES(346,'MLS','CF montreal',38,110,37,1);
INSERT INTO "classements" VALUES(347,'MLS','Toronto',38,108,36,2);
INSERT INTO "classements" VALUES(348,'MLS','Inter miami',38,105,35,3);
INSERT INTO "classements" VALUES(349,'MLS','los langeles',38,102,34,4);
INSERT INTO "classements" VALUES(350,'MLS','Cincinnati',38,99,33,5);
INSERT INTO "classements" VALUES(351,'MLS','Nashville',38,96,32,6);
INSERT INTO "classements" VALUES(352,'MLS','Orlando',38,93,31,7);
INSERT INTO "classements" VALUES(353,'MLS','Dc united',38,90,30,8);
INSERT INTO "classements" VALUES(354,'MLS','Houston',38,90,30,8);
INSERT INTO "classements" VALUES(355,'MLS','Dallas',38,84,28,10);

INSERT INTO "classements" VALUES(356,'Ligue 1','Paris SG',38,101,37,1);
INSERT INTO "classements" VALUES(357,'Ligue 1','Marseille',38,98,36,2);
INSERT INTO "classements" VALUES(358,'Ligue 1','Lyon',38,95,35,3);
INSERT INTO "classements" VALUES(359,'Ligue 1','Nantes',38,92,34,4);
INSERT INTO "classements" VALUES(360,'Ligue 1','Rennes',38,89,33,5);
INSERT INTO "classements" VALUES(361,'Ligue 1','Lille',38,86,32,6);
INSERT INTO "classements" VALUES(362,'Ligue 1','Lens',38,83,31,7);
INSERT INTO "classements" VALUES(363,'Ligue 1','Monaco',38,80,30,8);
INSERT INTO "classements" VALUES(364,'Ligue 1','Toulouse',38,70,30,8);
INSERT INTO "classements" VALUES(365,'Ligue 1','Brest',38,64,28,10);



COMMIT;
